name: Update Test Branch

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the action every day at midnight. Adjust the schedule as needed.
  workflow_dispatch:  # This allows you to manually trigger the workflow from the Actions tab.

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Pull Request Number
        id: get_pr
        run: echo "::set-output name=pr_number::${{ github.event.pull_request.number }}"

      - name: Update branch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const prNumber = ${{ steps.get_pr.outputs.pr_number }};
            const { context, getOctokit } = require('@actions/github');
            const octokit = getOctokit(process.env.GITHUB_TOKEN);
            
            const pr = await octokit.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            
            const baseBranch = pr.data.base.ref;
            const headBranch = pr.data.head.ref;
            
            await octokit.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: headBranch,
              head: baseBranch,
            });

      - name: Merge Pull Request
        if: ${{ steps.get_pr.outputs.pr_number }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const prNumber = ${{ steps.get_pr.outputs.pr_number }};
            const { context, getOctokit } = require('@actions/github');
            const octokit = getOctokit(process.env.GITHUB_TOKEN);

            await octokit.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
